name: CI Test Fortune Avenue and deploy to Netlify

on: 
  push: 
    branches: [ main ]

jobs: 
  test: 
    runs-on: ubuntu-latest 

    strategy: 
      matrix: 
        node-version: [ 18.x, 20.x, 22.x ]

    steps: 
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with: 
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Installation des dependances 
      run: npm install 

    - name: Lancement du linter 
      run: npm run lint

    - name: Lancement des tests Jest 
      run: npm test 

    - name: Déploiement sur Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: '.' # dossier racine projet 
        production-deploy: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}